### ISSUE TITLE
Bindgen Refactor

### ISSUE THREAD

**Issue by bhelx** [dylibso/xtp-rust-bindgen#16]
See https://github.com/dylibso/xtp/issues/887

The Go PR maybe be the closest analogue https://github.com/dylibso/xtp-go-bindgen/pull/22

**Comment by chrisdickinson** [comment]
Adding a note for @zshipko here – if we can swap from `std::collections::HashMap` to `serde_json::Map`, we can let plugin developers (optionally) preserve key order where it's important to them. (@G4Vi's c++ bindgen pr just reminded me of this!)

**Comment by zshipko** [comment]
Closing, this is done in #18
