### ISSUE TITLE
A struct with a buffer crashes deserialization

### ISSUE THREAD

**Issue by evacchi** [dylibso/xtp-rust-bindgen#3]
The following:

```yaml
version: v1-draft
components:
  schemas:
    Header:
      properties:
        key:
          type: string
        value:
          type: buffer
      description: A key/value header pair.
    Record:
      properties:
        topic:
          type: string
        key:
          type: buffer
        value:
          type: buffer
        headers:
          type: array
          items:
            $ref: "#/components/schemas/Header"
      description: A plain key/value record.

```

generates:

```rust
#[derive(Serialize, Deserialize, FromBytes, ToBytes)]
#[encoding(Json)]
pub struct Record {
    #[serde(rename = "headers")]
    pub headers: Vec<Header>,
    #[serde(rename = "key")]
    pub key: Vec<u8>,
    #[serde(rename = "topic")]
    pub topic: String,
    #[serde(rename = "value")]
    pub value: Vec<u8>,
}
```

the key, value buffers are encoded as a String. This causes the deserializer to crash while deserializing the _key_:

```
invalid type: string "dGhlLWtleQ==", expected a sequence at line 1 column 48
```

the base64 string decodes as `the-key` (the value for `{"key":"the-key"}` in the original payload)

I am not an expert with Rust, but I believe we're missing some bits :) Rewriting the struct as:

```rust
#[derive(Serialize, Deserialize, FromBytes, ToBytes)]
#[encoding(Json)]
pub struct Record {
    #[serde(rename = "headers")]
    pub headers: Vec<Header>,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "topic")]
    pub topic: String,
    #[serde(rename = "value")]
    pub value: String,
}
```

allows to decode it successfully, and then key, value can be manually base64-decoded in userland.

**Comment by evacchi** [comment]
this might be a solution (I tried, it works) https://docs.rs/base64-serde/0.7.0/base64_serde/macro.base64_serde_type.html

```rust
base64_serde_type!(Base64Standard, base64::engine::general_purpose::STANDARD);

#[derive(serde::Serialize, serde::Deserialize)]
struct ByteHolder {
    #[serde(with = "Base64Standard")]
    bytes: Vec<u8>,
}
```

**Comment by evacchi** [comment]
Worth noting that the same example also crashes if `key` is missing; fixable by specifying a policy to deal with that case, e.g.:

```
    #[serde(rename = "key", default)]
    pub key: String,

```

**Comment by nilslice** [comment]
> Worth noting that the same example also crashes if key is missing; fixable by specifying a policy to deal with that case, e.g.:

Is this a `nullable` field in the schema? If the host doesn't set the field to be nullable, I think we always expect the value to be there.

**Comment by nilslice** [comment]
> the key, value buffers are encoded as a String. This causes the deserializer to crash while deserializing the key:

Wouldn't you want to set this field in the schema to `string` then? Is there a reason its raw buffer instead?

**Comment by evacchi** [comment]
> Is this a nullable field in the schema? If the host doesn't set the field to be nullable, I think we always expect the value to be there.

I did not, my bad 😬 I just assumed nullable was the default

**Comment by evacchi** [comment]
> Wouldn't you want to set this field in the schema to `string` then?

right, I meant that the JSON serializer on the host end encodes both fields as strings, but `value` is a data field encoded as a base64-encoded string, which should correspond to a `buffer` on the guest end (?) -- at least this is how it works in Go? 🤔 

```
// A plain key/value record.
type Record struct {
	Headers []Header `json:"headers"`
	Key     []byte   `json:"key"`
	Topic   string   `json:"topic"`
	Value   []byte   `json:"value"`
}
```

(My Go bias might also be the reason why I assumed nullability is the default)

**Comment by evacchi** [comment]
clarified offline: currently the behavior is essentially left to the language-specific implementation; we should just decide a common behavior across languages.
